import { useEffect,useState } from 'react';
import { formatCentsCompact,type PublicCityPageDto } from '@streets/shared';
import { Link,useParams } from 'react-router-dom';
import { PublicApiError,publicSiteApi } from '../api/public.js';
import { PublicError,PublicLoading,PublicPageHero,PublicStatGrid } from '../components/PublicPageBits.js';

export function CityPage(){const{citySlug=''}=useParams();const[data,setData]=useState<PublicCityPageDto|null>(null);const[missing,setMissing]=useState(false);const[failed,setFailed]=useState(false);useEffect(()=>{let live=true;void publicSiteApi.city(citySlug).then(x=>live&&setData(x.city)).catch(e=>{if(!live)return;e instanceof PublicApiError&&e.status===404?setMissing(true):setFailed(true)});return()=>{live=false}},[citySlug]);
if(missing)return <div className="site-page"><PublicPageHero eyebrow="City profile" title="City not found"/></div>;
return <div className="site-page"><PublicPageHero eyebrow={data?.trait??'City profile'} title={data?.name??'City'}>{data?<p>{data.blurb}</p>:null}</PublicPageHero><section className="site-section site-section--tight"><div className="container public-game-stack">{!data&&!failed?<PublicLoading/>:null}{failed?<PublicError/>:null}{data?<><PublicStatGrid stats={[['Players',String(data.playerCount)],['Economy',formatCentsCompact(data.economyNetWorthCents)],['Turf Held',`${data.turfBlocksHeld}/${data.turfBlocksTotal}`]]}/><section className="site-panel"><div className="site-panel__head"><div><span className="site-card__eyebrow">Street talk</span><h2>What people know</h2></div></div><ul className="site-feature-list">{data.talk.map(x=><li key={x}>{x}</li>)}</ul></section><section className="site-panel"><div className="site-panel__head"><div><span className="site-card__eyebrow">Districts</span><h2>Current turf</h2></div></div><div className="district-grid">{data.districts.map(d=><article className="district-card" key={d.key}><span className="site-card__eyebrow">{d.key}</span><h3>{d.name}</h3><p>{d.blurb??'District'}</p><div className="district-card__holder">{d.holder?<><strong>{d.holder.alliance?`[${d.holder.alliance.tag}] `:''}{d.holder.displayName}</strong><Link to={`/players/${d.holder.publicPimpId}`}>Player #{d.holder.publicPimpId}</Link></>:<strong>Locals / Unclaimed</strong>}</div></article>)}</div></section></>:null}</div></section></div>}
