import { useEffect,useState } from 'react';
import type { PublicTurfDto } from '@streets/shared';
import { Link } from 'react-router-dom';
import { publicSiteApi } from '../api/public.js';
import { PublicError,PublicLoading,PublicPageHero } from '../components/PublicPageBits.js';
import { PublicEvents } from '../components/PublicGameBlocks.js';

export function TurfPage(){const[data,setData]=useState<PublicTurfDto|null>(null);const[failed,setFailed]=useState(false);useEffect(()=>{let live=true;void publicSiteApi.turf().then(x=>live&&setData(x)).catch(()=>live&&setFailed(true));return()=>{live=false}},[]);
return <div className="site-page"><PublicPageHero eyebrow="Territory" title="Turf"><p>See who controls each public district and the latest completed captures.</p></PublicPageHero><section className="site-section site-section--tight"><div className="container public-game-stack">{!data&&!failed?<PublicLoading/>:null}{failed?<PublicError/>:null}{data?<>{!data.enabled?<PublicError title="Turf is not enabled in the current ruleset."/>:<><section className="site-panel"><div className="site-panel__head"><div><span className="site-card__eyebrow">Current control</span><h2>Blocks</h2></div></div><div className="turf-grid">{data.blocks.map(b=><article className="turf-block" key={b.city.slug+':'+b.district}><span>{b.city.name}</span><h3>{b.districtName}</h3>{b.holder?<><strong>{b.holder.alliance?`[${b.holder.alliance.tag}] `:''}{b.holder.displayName}</strong><Link to={`/players/${b.holder.publicPimpId}`}>#{b.holder.publicPimpId}</Link></>:<strong>Locals / Unclaimed</strong>}</article>)}</div></section><section className="site-panel"><div className="site-panel__head"><div><span className="site-card__eyebrow">Street wire</span><h2>Recent captures</h2></div></div><PublicEvents game={{round:data.round!,ruleset:{id:'',version:'',name:''},stats:{players:0,alliances:0,cities:0,turfBlocksHeld:0,turfBattles:0,economyNetWorthCents:0},topRankings:[],recentEvents:data.recentCaptures,recentNews:[]}} /></section></>}</>}</>:null}</div></section></div>}
