ALTER TYPE "ActivityType" ADD VALUE 'HIDEOUT_UPGRADE';

ALTER TABLE "RoundPlayer"
  ADD COLUMN "hideoutSafeRoomLevel" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "hideoutLookoutsLevel" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "hideoutWorkshopLevel" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "hideoutBackOfficeLevel" INTEGER NOT NULL DEFAULT 0;
