import { describe, expect, it } from 'vitest';
import type { GameActionResult, PlayerSnapshot, ProduceCrackResult, ScoutResult, WorkSupplyPlanDto } from '@streets/shared';
import { produceReceiptLines, scoutReceiptLines } from '../actionReceipts.js';

const products = [{ key: 'CRACK', name: 'Crack', quantity: 120 }];

const resources = {
  cashCents: 1_000_000,
  whores: 10,
  thugs: 8,
  fitThugs: 8,
  woundedThugs: 0,
  postedThugs: 0,
  armedThugs: 6,
  unarmedThugs: 2,
  condoms: 50,
  medicine: 7,
  product: 120,
  crack: 120,
  beer: 30,
  pistols: 6,
  shotguns: 0,
  tek9s: 0,
  ak47s: 0,
  lowRiders: 0,
};

const before: PlayerSnapshot = {
  cashCents: 1_000_000,
  netWorthCents: 2_000_000,
  turns: 144,
  whoreHappiness: 70,
  thugHappiness: 80,
  resources,
};

const after: PlayerSnapshot = {
  cashCents: 1_003_000,
  netWorthCents: 2_010_000,
  turns: 100,
  whoreHappiness: 68,
  thugHappiness: 77,
  resources: {
    ...resources,
    cashCents: 1_003_000,
    whores: 12,
    thugs: 9,
    condoms: 42,
    medicine: 5,
    product: 115,
    crack: 115,
    beer: 25,
  },
};

const supply: WorkSupplyPlanDto = {
  job: 'CASINO',
  role: 'hoes',
  policy: { primary: 'ECSTASY', fallback: 'CRACK', emergency: null, strict: false },
  need: 10,
  perTurn: 1,
  takeMultiplier: 0.9,
  recruitmentMultiplier: 1.2,
  departureMultiplier: 0.8,
  morale: 0,
  woundMultiplier: 1,
  heat: 6,
  switchesAtTurn: 4,
  consumed: { ECSTASY: 4, CRACK: 3 },
  slices: [
    { product: 'ECSTASY', productName: 'Ecstasy', state: 'supplied', units: 4, share: 0.4, turns: 4, takeMultiplier: 1.1, recruitmentMultiplier: 1.4, departureMultiplier: 0.6, morale: 0, heat: 4, woundMultiplier: 1 },
    { product: 'CRACK', productName: 'Crack', state: 'substituted', units: 3, share: 0.3, turns: 3, takeMultiplier: 1, recruitmentMultiplier: 1, departureMultiplier: 1, morale: 0, heat: 2, woundMultiplier: 1 },
    { product: null, productName: null, state: 'dry', units: 3, share: 0.3, turns: 3, takeMultiplier: 0.6, recruitmentMultiplier: 1, departureMultiplier: 1.5, morale: 0, heat: 0, woundMultiplier: 1 },
  ],
};

const cook: WorkSupplyPlanDto = {
  ...supply,
  job: 'COOK',
  role: 'thugs',
  need: 8,
  perTurn: 0.8,
  takeMultiplier: 1.3,
  recruitmentMultiplier: 1,
  departureMultiplier: 0.5,
  morale: 20,
  heat: 3,
  consumed: { COCAINE: 8 },
  slices: [
    { product: 'COCAINE', productName: 'Cocaine', state: 'supplied', units: 8, share: 1, turns: 10, takeMultiplier: 1.3, recruitmentMultiplier: 1, departureMultiplier: 0.5, morale: 20, heat: 3, woundMultiplier: 1 },
  ],
};

const heat = {
  before: 80,
  added: 12,
  after: 52,
  max: 100,
  takeMultiplier: 0.75,
  bustChance: 0.25,
  busted: false,
  arrested: true,
  arrestChance: 0.15,
  lockedUntil: '2026-09-20T12:00:00.000Z',
  seized: { CRACK: 5, ECSTASY: 2 },
  fineCents: 12_500,
};

function action<T>(result: T): GameActionResult<T> {
  return {
    success: true,
    action: 'TEST',
    before,
    after,
    changes: [],
    result,
  };
}

describe('action receipt lines', () => {
  it('covers every scouting result field players need to see', () => {
    const result: ScoutResult = {
      district: { key: 'CASINO', slug: 'casino', name: 'Casino District', protectionWhoresPerThug: 4, coveredWhores: 24, exposedFraction: 0, armedThugs: 6, unarmedThugs: 2, requiresArmedThugs: true },
      supply,
      heat,
      whoresRecruited: 4,
      thugsRecruited: 2,
      grossEarnedCents: 9_000,
      crewTakeCents: 4_500,
      cashEarnedCents: 4_500,
      hideoutBonusCents: 500,
      payoutPercent: 50,
      crackFound: 7,
      condomsUsed: 8,
      crackUsed: 4,
      beerUsed: 5,
      condomsMissing: 2,
      beerMissing: 3,
      whoresLeft: 1,
      thugsLeft: 1,
      infected: 3,
      treated: 2,
      medicineUsed: 2,
      lostToInfection: 1,
      exposedFraction: 0,
      coveredWhores: 24,
      armedThugs: 6,
      unarmedThugs: 2,
      turnsUsed: 44,
      turnsRemaining: 100,
    };

    expect(scoutReceiptLines(action(result), { products }).map((line) => line.label)).toEqual([
      'Turns used',
      'Supply',
      'Ecstasy used',
      'Supply effects',
      'Restock',
      'Heat',
      'Heat drag',
      'ARRESTED',
      'Seized',
      'Fine',
      'Locked up',
      'Brought in',
      'Their cut (50%)',
      'Your cut',
      'Back Office bonus',
      'Whores recruited',
      'Thugs recruited',
      'Crack found',
      'Condoms used',
      'Worked without condoms',
      'Crack used',
      'Beer used',
      'Worked without beer',
      'Caught something',
      'Treated with medicine',
      'Lost, no medicine',
      'Medicine',
      'Whores walked out',
      'Thugs walked out',
      'Armed street cover',
      'Turns remaining',
    ]);
  });

  it('covers every production result field players need to see', () => {
    const result: ProduceCrackResult = {
      supply,
      cook,
      heat,
      productType: 'METH',
      productName: 'Meth',
      productProduced: 12,
      hideoutBonusProduct: 2,
      crackProduced: 0,
      ingredientCents: 6_000,
      limitedByCash: true,
      grossEarnedCents: 5_000,
      crewTakeCents: 2_500,
      cashEarnedCents: 2_500,
      hideoutBonusCents: 250,
      payoutPercent: 50,
      crackFound: 3,
      condomsUsed: 8,
      crackUsed: 4,
      beerUsed: 5,
      condomsMissing: 2,
      beerMissing: 3,
      whoresLeft: 1,
      thugsLeft: 1,
      infected: 3,
      treated: 2,
      medicineUsed: 2,
      lostToInfection: 1,
      turnsUsed: 44,
      turnsRemaining: 100,
    };

    expect(produceReceiptLines(action(result), { products }).map((line) => line.label)).toEqual([
      'Supply',
      'Ecstasy used',
      'Supply effects',
      'Restock',
      'Cooks: Supply',
      'Cooks: Cocaine used',
      'Cooks: Supply effects',
      'Heat',
      'Heat drag',
      'ARRESTED',
      'Seized',
      'Fine',
      'Locked up',
      'Turns used',
      'Meth produced',
      'Workshop bonus',
      'Ingredients',
      'Short on cash',
      'Brought in',
      'Their cut (50%)',
      'Your cut',
      'Back Office bonus',
      'Crack found',
      'Condoms used',
      'Worked without condoms',
      'Crack used',
      'Beer used',
      'Worked without beer',
      'Caught something',
      'Treated with medicine',
      'Lost, no medicine',
      'Medicine',
      'Whores walked out',
      'Thugs walked out',
      'Turns remaining',
    ]);
  });
});
