import type { QuestDefinitionCatalog } from '../types.js';

/**
 * Quest roadmap Phase O: small repeatable contracts that rotate through the
 * ordinary game loop. They deliberately reuse existing activity rather than
 * adding daily-only actions.
 */
export const dailyContracts = {
  DAILY_STREET_SWEEP: {
    key: 'DAILY_STREET_SWEEP',
    title: 'Street Sweep',
    description: 'Mama wants a full street shift handled before the next reset.',
    contactKey: 'MAMA_KING',
    type: 'DAILY',
    category: 'STREET',
    difficulty: 'STREET_JOB',
    prerequisites: [],
    objectives: [{
      id: 'scout_turns',
      kind: 'SPEND_TURNS',
      description: 'Spend 25 turns Scouting.',
      target: 25,
      params: { eventTypes: ['SCOUT'] },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 1_000_000 },
      { kind: 'CONTACT_REP', key: 'MAMA_KING', amount: 2 },
    ],
    followUpKeys: [],
    repeatability: 'DAILY',
    expiresAfterMinutes: null,
    availability: { rotationPool: 'DAILY_CONTRACTS' },
  },

  DAILY_COOK_ORDER: {
    key: 'DAILY_COOK_ORDER',
    title: 'Cook Order',
    description: 'Pip has a small order that needs to be cooked and ready before the street changes over.',
    contactKey: 'PIP',
    type: 'DAILY',
    category: 'PRODUCT',
    difficulty: 'STREET_JOB',
    prerequisites: [],
    objectives: [{
      id: 'produce_product',
      kind: 'EVENT_SUM',
      description: 'Produce 100 units of product.',
      target: 100,
      params: { eventTypes: ['PRODUCE_CRACK'], field: 'product' },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 1_250_000 },
      { kind: 'CONTACT_REP', key: 'PIP', amount: 2 },
    ],
    followUpKeys: [],
    repeatability: 'DAILY',
    expiresAfterMinutes: null,
    availability: { rotationPool: 'DAILY_CONTRACTS' },
  },

  DAILY_CASH_TAKE: {
    key: 'DAILY_CASH_TAKE',
    title: 'Cash Take',
    description: 'Keep the crew earning. Mama only cares that clean street money keeps moving.',
    contactKey: 'MAMA_KING',
    type: 'DAILY',
    category: 'STREET',
    difficulty: 'STREET_JOB',
    prerequisites: [],
    objectives: [{
      id: 'earn_cash',
      kind: 'EARN_CASH',
      description: 'Earn $25,000 from street work or production.',
      target: 2_500_000,
      params: { eventTypes: ['SCOUT', 'WORK_STREETS', 'PRODUCE_CRACK'] },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'ITEM', key: 'condoms', amount: 500 },
      { kind: 'CONTACT_REP', key: 'MAMA_KING', amount: 2 },
    ],
    followUpKeys: [],
    repeatability: 'DAILY',
    expiresAfterMinutes: null,
    availability: { rotationPool: 'DAILY_CONTRACTS' },
  },

  DAILY_EYES_ON_TARGET: {
    key: 'DAILY_EYES_ON_TARGET',
    title: 'Eyes on Target',
    description: 'Tommy wants one fresh Recon report before the daily board turns over.',
    contactKey: 'TOMMY',
    type: 'DAILY',
    category: 'COMBAT',
    difficulty: 'CONTRACT',
    prerequisites: [],
    objectives: [{
      id: 'recon_once',
      kind: 'EVENT_COUNT',
      description: 'Complete 1 Recon.',
      target: 1,
      params: { eventTypes: ['COMBAT_RECON'] },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 750_000 },
      { kind: 'CONTACT_REP', key: 'TOMMY', amount: 2 },
      { kind: 'FAVOR_ITEM', key: 'BURNER_PHONE', amount: 1 },
    ],
    followUpKeys: [],
    repeatability: 'DAILY',
    expiresAfterMinutes: null,
    availability: { rotationPool: 'DAILY_CONTRACTS' },
  },

  DAILY_ROAD_MONEY: {
    key: 'DAILY_ROAD_MONEY',
    title: 'Road Money',
    description: 'Wheels has a lane open. Put one intercity run on the road before the window closes.',
    contactKey: 'WHEELS',
    type: 'DAILY',
    category: 'TRAVEL',
    difficulty: 'CONTRACT',
    prerequisites: [],
    objectives: [{
      id: 'launch_run',
      kind: 'EVENT_COUNT',
      description: 'Launch 1 intercity run.',
      target: 1,
      params: { eventTypes: ['RUN_LAUNCHED'] },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 1_000_000 },
      { kind: 'CONTACT_REP', key: 'WHEELS', amount: 2 },
    ],
    followUpKeys: [],
    repeatability: 'DAILY',
    expiresAfterMinutes: null,
    availability: { rotationPool: 'DAILY_CONTRACTS' },
  },

  DAILY_SUPPLY_RUN: {
    key: 'DAILY_SUPPLY_RUN',
    title: 'Supply Run',
    description: 'Keep the basics moving through the Corner Store and Mama will make sure some medicine comes back your way.',
    contactKey: 'MAMA_KING',
    type: 'DAILY',
    category: 'ECONOMY',
    difficulty: 'STREET_JOB',
    prerequisites: [],
    objectives: [{
      id: 'buy_supplies',
      kind: 'EVENT_SUM',
      description: 'Buy $10,000 of supplies from the Corner Store.',
      target: 1_000_000,
      params: { eventTypes: ['STORE_BUY'], field: 'totalCents', where: { storeKey: 'CORNER' } },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'ITEM', key: 'medicine', amount: 10 },
      { kind: 'CONTACT_REP', key: 'MAMA_KING', amount: 2 },
    ],
    followUpKeys: [],
    repeatability: 'DAILY',
    expiresAfterMinutes: null,
    availability: { rotationPool: 'DAILY_CONTRACTS' },
  },

  DAILY_MOVE_PRODUCT: {
    key: 'DAILY_MOVE_PRODUCT',
    title: 'Move Product',
    description: 'Pip wants volume, not a speech. Move one hundred units across his counter before reset.',
    contactKey: 'PIP',
    type: 'DAILY',
    category: 'PRODUCT',
    difficulty: 'CONTRACT',
    prerequisites: [],
    objectives: [{
      id: 'sell_product',
      kind: 'EVENT_SUM',
      description: 'Sell 100 units of product to Pip.',
      target: 100,
      params: { eventTypes: ['STORE_SELL'], field: 'quantity', where: { storeKey: 'PIP' } },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 1_500_000 },
      { kind: 'CONTACT_REP', key: 'PIP', amount: 2 },
      { kind: 'FAVOR_ITEM', key: 'COOKHOUSE_RUSH', amount: 1 },
    ],
    followUpKeys: [],
    repeatability: 'DAILY',
    expiresAfterMinutes: null,
    availability: { rotationPool: 'DAILY_CONTRACTS' },
  },

  DAILY_TWO_SHIFTS: {
    key: 'DAILY_TWO_SHIFTS',
    title: 'Two Shifts',
    description: 'Blocks wants to see the crew actually working the city, not just talking about it.',
    contactKey: 'BLOCKS',
    type: 'DAILY',
    category: 'STREET',
    difficulty: 'STREET_JOB',
    prerequisites: [],
    objectives: [{
      id: 'work_two_shifts',
      kind: 'EVENT_COUNT',
      description: 'Complete 2 Scout or street-work shifts.',
      target: 2,
      params: { eventTypes: ['SCOUT', 'WORK_STREETS'] },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 750_000 },
      { kind: 'ITEM', key: 'beer', amount: 100 },
      { kind: 'CONTACT_REP', key: 'BLOCKS', amount: 2 },
    ],
    followUpKeys: [],
    repeatability: 'DAILY',
    expiresAfterMinutes: null,
    availability: { rotationPool: 'DAILY_CONTRACTS' },
  },
} as const satisfies QuestDefinitionCatalog;
