import type { QuestDefinitionCatalog } from '../types.js';

/**
 * Quest roadmap Phase Q: one-time Jobs that do not exist on the player's board
 * until unusual server-authoritative conditions expose them.
 */
export const secretQuests = {
  SECRET_RED_LINE: {
    key: 'SECRET_RED_LINE',
    title: 'The Red Line',
    description: 'Vic only calls when the sirens stop sounding like background noise. You ran the Heat high enough to get his attention; now prove you can cool the block without disappearing.',
    contactKey: 'VIC',
    type: 'SECRET',
    category: 'HEAT',
    difficulty: 'HIGH_RISK',
    prerequisites: [],
    objectives: [
      {
        id: 'bribe_heat',
        kind: 'EVENT_SUM',
        description: 'Bribe away 20 Heat.',
        target: 20,
        params: { eventTypes: ['HEAT_BRIBE'], field: 'points' },
      },
      {
        id: 'bribe_count',
        kind: 'EVENT_COUNT',
        description: 'Make 2 successful Heat bribes.',
        target: 2,
        params: { eventTypes: ['HEAT_BRIBE'] },
      },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 3_000_000 },
      { kind: 'FAVOR_ITEM', key: 'BURNER_PHONE', amount: 1 },
      { kind: 'CONTACT_REP', key: 'VIC', amount: 20 },
    ],
    followUpKeys: [],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {
      hidden: true,
      secretTrigger: { kind: 'STATE_AT_LEAST', field: 'heat', target: 80 },
    },
  },

  SECRET_BLOOD_IN_WATER: {
    key: 'SECRET_BLOOD_IN_WATER',
    title: 'Blood in the Water',
    description: 'Tommy heard the same story three times: your crew went out looking for blood and came home lighter. He has work for somebody willing to answer that reputation.',
    contactKey: 'TOMMY',
    type: 'SECRET',
    category: 'COMBAT',
    difficulty: 'HIGH_RISK',
    prerequisites: [],
    objectives: [{
      id: 'raid_wins',
      kind: 'WIN_EVENTS',
      description: 'Win 2 raids as the attacker.',
      target: 2,
      params: { eventTypes: ['RAID_ATTACK'] },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 3_500_000 },
      { kind: 'FAVOR_ITEM', key: 'TOMMY_VOUCHER', amount: 2 },
      { kind: 'CONTACT_REP', key: 'TOMMY', amount: 20 },
    ],
    followUpKeys: [],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {
      hidden: true,
      secretTrigger: {
        kind: 'ACTIVITY_COUNT',
        eventTypes: ['RAID_ATTACK'],
        where: { won: false },
        target: 3,
      },
    },
  },

  SECRET_ONE_PHONE_CALL: {
    key: 'SECRET_ONE_PHONE_CALL',
    title: 'One Phone Call',
    description: 'An arrest changes who answers the phone. Vic wants to see whether you can put a crew back on the road and get everybody home without another badge touching the car.',
    contactKey: 'VIC',
    type: 'SECRET',
    category: 'TRAVEL',
    difficulty: 'SERIOUS_BUSINESS',
    prerequisites: [],
    objectives: [{
      id: 'clean_return',
      kind: 'EVENT_COUNT',
      description: 'Bring one run home without a road incident.',
      target: 1,
      params: { eventTypes: ['RUN_RETURNED'], where: { incidents: [] } },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 3_000_000 },
      { kind: 'FAVOR_ITEM', key: 'BURNER_PHONE', amount: 1 },
      { kind: 'CONTACT_REP', key: 'VIC', amount: 20 },
    ],
    followUpKeys: [],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {
      hidden: true,
      secretTrigger: {
        kind: 'ACTIVITY_COUNT',
        eventTypes: ['RUN_INCIDENT'],
        where: { kind: 'ARREST' },
        target: 1,
      },
    },
  },

  SECRET_HEAVY_FREIGHT: {
    key: 'SECRET_HEAVY_FREIGHT',
    title: 'Heavy Freight',
    description: 'Wheels heard about the trunk that came home heavy enough to make the suspension complain. One big haul gets attention; repeated road work gets respect.',
    contactKey: 'WHEELS',
    type: 'SECRET',
    category: 'TRAVEL',
    difficulty: 'SERIOUS_BUSINESS',
    prerequisites: [],
    objectives: [
      {
        id: 'returns',
        kind: 'EVENT_COUNT',
        description: 'Bring 3 intercity runs home.',
        target: 3,
        params: { eventTypes: ['RUN_RETURNED'] },
      },
      {
        id: 'road_turns',
        kind: 'EVENT_SUM',
        description: 'Accumulate 30 turns of road travel on returned runs.',
        target: 30,
        params: { eventTypes: ['RUN_RETURNED'], field: 'turnsSpent' },
      },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 4_000_000 },
      { kind: 'ITEM', key: 'lowRiders', amount: 1 },
      { kind: 'CONTACT_REP', key: 'WHEELS', amount: 20 },
    ],
    followUpKeys: [],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {
      hidden: true,
      secretTrigger: {
        kind: 'ACTIVITY_OBJECT_SUM_AT_LEAST',
        eventTypes: ['RUN_RETURNED'],
        field: 'cargoBack',
        target: 500,
      },
    },
  },

  SECRET_HOUSE_FULL: {
    key: 'SECRET_HOUSE_FULL',
    title: 'House Full',
    description: 'A thousand hoes changes the sound of a city. Mama has stopped asking whether you can build a street operation; now she wants to know whether you can keep one that size earning.',
    contactKey: 'MAMA_KING',
    type: 'SECRET',
    category: 'STREET',
    difficulty: 'KINGPIN_CONTRACT',
    prerequisites: [],
    objectives: [{
      id: 'street_take',
      kind: 'EARN_CASH',
      description: 'Earn $750,000 from Scout or street-work shifts.',
      target: 75_000_000,
      params: { eventTypes: ['SCOUT', 'WORK_STREETS'] },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 5_000_000 },
      { kind: 'FAVOR_ITEM', key: 'MAMA_ADVICE', amount: 2 },
      { kind: 'CONTACT_REP', key: 'MAMA_KING', amount: 25 },
    ],
    followUpKeys: [],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {
      hidden: true,
      secretTrigger: { kind: 'STATE_AT_LEAST', field: 'whores', target: 1_000 },
    },
  },

  SECRET_CORNER_KING: {
    key: 'SECRET_CORNER_KING',
    title: 'Corner King',
    description: 'Three blocks under one name is when Blocks stops calling it luck. Hold the line, take ground from somebody who wants it, and put muscle where the map says your name.',
    contactKey: 'BLOCKS',
    type: 'SECRET',
    category: 'TURF',
    difficulty: 'KINGPIN_CONTRACT',
    prerequisites: [],
    objectives: [
      {
        id: 'push_wins',
        kind: 'WIN_EVENTS',
        description: 'Win 2 settled turf pushes as the attacker.',
        target: 2,
        params: { eventTypes: ['TURF_PUSH_ATTACK'] },
      },
      {
        id: 'post_thugs',
        kind: 'EVENT_SUM',
        description: 'Post 25 thugs onto turf you hold.',
        target: 25,
        params: { eventTypes: ['TURF_POST'], field: 'thugs' },
      },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 5_000_000 },
      { kind: 'FAVOR_ITEM', key: 'DOCTOR_FAVOR', amount: 1 },
      { kind: 'CONTACT_REP', key: 'BLOCKS', amount: 25 },
    ],
    followUpKeys: [],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {
      hidden: true,
      secretTrigger: { kind: 'TURF_COUNT_AT_LEAST', target: 3 },
    },
  },

  SECRET_SEVEN_FIGURES: {
    key: 'SECRET_SEVEN_FIGURES',
    title: 'Seven Figures',
    description: 'Pip does not care what the leaderboard calls you. Once the books cross seven figures, he starts talking to you like somebody who can move serious money through the counter.',
    contactKey: 'PIP',
    type: 'SECRET',
    category: 'PRODUCT',
    difficulty: 'KINGPIN_CONTRACT',
    prerequisites: [],
    objectives: [{
      id: 'pip_sales',
      kind: 'EVENT_SUM',
      description: 'Sell $500,000 of product to Pip.',
      target: 50_000_000,
      params: { eventTypes: ['STORE_SELL'], field: 'totalCents', where: { storeKey: 'PIP' }, display: 'CURRENCY' },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 5_000_000 },
      { kind: 'FAVOR_ITEM', key: 'PIP_CONNECTION', amount: 2 },
      { kind: 'CONTACT_REP', key: 'PIP', amount: 25 },
    ],
    followUpKeys: [],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {
      hidden: true,
      secretTrigger: { kind: 'STATE_AT_LEAST', field: 'netWorthCents', target: 100_000_000 },
    },
  },
} as const satisfies QuestDefinitionCatalog;
