/**
 * 1.6.0-G. Where a full dealer crew pays best for each product, city by city, and how far the
 * cheapest supplier is: the gate is that no city is the best market for everything, every
 * product has a second market making at least half what the best does, and each new city has a reason to drive there.
 *
 *   npm run qa:supply-cities -- [--ruleset classic-og-v1.6-g] [--output docs/SUPPLY-CITIES-1.6.0-G.md]
 */
import { writeFile } from 'node:fs/promises';
import { rulesets, type Ruleset } from '@streets/rulesets';
import { dealerDemand, dealerPace, dealerPressure, dealerRules, dealerStreetPriceCents, findRoutes } from '@streets/rules-engine';

const args = process.argv.slice(2);
const flag = (name: string) => { const at = args.indexOf(name); return at >= 0 ? args[at + 1] : undefined; };
const ruleset = rulesets[flag('--ruleset') ?? 'classic-og-v1.6-g'] as Ruleset | undefined;
if (!ruleset) throw new Error('Unknown ruleset.');
const rules = dealerRules(ruleset);
if (!rules) throw new Error('That ruleset has no dealer crews.');
const NEW = ['chicago', 'tulsa', 'dallas'];
const DEALERS = 6;

const cities = Object.keys(ruleset.cities ?? {});
const suppliers = ruleset.supplyNetwork?.suppliers ?? [];
const products = [...new Set(suppliers.flatMap((supplier) => Object.keys(supplier.offers)))];
const name = (slug: string) => ruleset.cities?.[slug]?.name ?? slug;
const money = (cents: number) => `$${Math.round(cents / 100).toLocaleString('en-US')}`;
const hours = (from: string, to: string) => (from === to ? 0 : findRoutes(ruleset, from, to)[0]?.driveHours ?? Infinity);

interface Market { city: string; street: number; demand: number; perHour: number; supplier: string; cost: number; drive: number }
const table = new Map<string, Market[]>();
for (const product of products) {
  const sources = suppliers.flatMap((supplier) => (supplier.offers[product] ? [{ supplier, cost: supplier.offers[product]!.unitCostCents }] : []));
  const rows = cities.map((city): Market => {
    const street = dealerStreetPriceCents(ruleset, rules, city, product) ?? 0;
    const pace = dealerPace({ rules, demand: dealerDemand(ruleset, city, product), district: 'URBAN_GHETTO', dealers: Array(DEALERS).fill(0), priceCents: street, streetPriceCents: street, pressure: dealerPressure(ruleset, city) });
    // The source that leaves the most per unit once the drive is counted: an hour on the road costs an hour of sales.
    const best = sources.map(({ supplier, cost }) => ({ supplier, cost, drive: hours(supplier.citySlug, city) }))
      .sort((a, b) => a.cost - b.cost || a.drive - b.drive)[0]!;
    const perUnit = street * (1 - pace.cutPercent / 100) - best.cost;
    return { city, street, demand: dealerDemand(ruleset, city, product), perHour: pace.unitsPerHour * perUnit - pace.operatingCentsPerHour, supplier: best.supplier.name, cost: best.cost, drive: best.drive };
  }).sort((a, b) => b.perHour - a.perHour);
  table.set(product, rows);
}

const problems: string[] = [];
const winners = products.map((product) => table.get(product)![0]!.city);
if (new Set(winners).size === 1) problems.push(`${name(winners[0]!)} is the best market for every product.`);
for (const product of products) {
  const [first, second] = table.get(product)!;
  if (!second || second.perHour < first!.perHour * 0.5) problems.push(`${product}: only ${name(first!.city)} is worth selling in (next best under half).`);
}
for (const city of NEW.filter((slug) => cities.includes(slug))) {
  const topThree = products.filter((product) => table.get(product)!.slice(0, 3).some((row) => row.city === city));
  const supplier = suppliers.some((entry) => entry.citySlug === city);
  const cheapRoom = (() => {
    const homes = Object.entries(ruleset.supplyNetwork?.properties?.cities ?? {});
    const perUnit = homes.map(([slug, row]) => [slug, row.warehouse.costCents / row.warehouse.capacityUnits] as const).sort((a, b) => a[1] - b[1]);
    return perUnit[0]?.[0] === city;
  })();
  if (!topThree.length && !supplier && !cheapRoom) problems.push(`${name(city)} gives no reason to drive there.`);
}

const lines = [
  `# Supply cities — ${ruleset.meta.version}`,
  '',
  `Generated by \`npm run qa:supply-cities -- --ruleset ${ruleset.meta.id}\`. A full crew of ${DEALERS} new dealers in an ordinary district, asking the street price, stocked from the cheapest supplier. Net an hour is after the dealers' cut, wages and wholesale; it ignores the trip, which the drive column shows.`,
  '',
];
for (const product of products) {
  lines.push(`## ${ruleset.products?.[product]?.name ?? product}`, '', '| City | Street price | Demand | Net an hour | Cheapest source | Drive from it |', '| --- | ---: | ---: | ---: | --- | ---: |');
  for (const row of table.get(product)!) {
    lines.push(`| ${name(row.city)}${NEW.includes(row.city) ? ' (new)' : ''} | ${money(row.street)} | ${row.demand} | ${money(row.perHour)} | ${row.supplier} (${money(row.cost)}) | ${row.drive === 0 ? 'here' : `${row.drive}h`} |`);
  }
  lines.push('');
}
lines.push('## Gate', '', problems.length ? problems.map((problem) => `- ${problem}`).join('\n') : 'Passed: no city is the best market for everything, every product has a second market making at least half what the best does, and every new city has a reason to drive there.', '');
const report = lines.join('\n');
const output = flag('--output');
if (output) await writeFile(output, report);
if (!args.includes('--quiet')) console.log(report);
if (problems.length) process.exitCode = 1;
