/**
 * 1.5.x. Bakes the travel road map's backdrop: the lower 48 from the US Census boundaries in
 * us-atlas (public domain), its state lines, and where each game city really sits, all in the
 * map's own 400-wide coordinates. The browser never loads the atlas; it reads the generated
 * module. Rerun after adding a city:
 *
 *   node scripts/art/build-usa-map.mjs
 */
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { geoAlbersUsa, geoPath } from 'd3-geo';
import { feature, merge, mesh } from 'topojson-client';

const require = createRequire(import.meta.url);
const atlas = JSON.parse(await readFile(require.resolve('us-atlas/states-albers-10m.json'), 'utf8'));
const OUT = new URL('../../apps/web/src/components/usaMap.generated.ts', import.meta.url);
const WIDTH = 400;
const PAD = 6;

/** Real city centres. Beverly Hills sits inside LA, so it is nudged apart below to stay clickable. */
const CITIES = {
  'seattle': [-122.3321, 47.6062],
  'los-angeles': [-118.2437, 34.0522],
  'beverly-hills': [-118.4004, 34.0736],
  'las-vegas': [-115.1398, 36.1699],
  'detroit': [-83.0458, 42.3314],
  'new-york-city': [-74.006, 40.7128],
  'atlanta': [-84.388, 33.749],
  'miami-beach': [-80.13, 25.7907],
};
/** Map-unit nudges where two real cities would share a dot. */
const NUDGE = { 'beverly-hills': [-9, 7], 'los-angeles': [3, -3] };

// The lower 48 only: Alaska (02), Hawaii (15) and the territories have no game cities.
const lower48 = (geometry) => !['02', '15', '60', '66', '69', '72', '78'].includes(String(geometry.id).slice(0, 2));
const states = { ...atlas.objects.states, geometries: atlas.objects.states.geometries.filter(lower48) };
// One closed shape for the land fill; the lines between states drawn over it.
const land = merge(atlas, states.geometries);
const borders = mesh(atlas, states, (a, b) => a !== b);

// us-atlas's albers files are pre-projected with this exact projection, so cities line up.
const projection = geoAlbersUsa().scale(1300).translate([487.5, 305]);

const bounds = geoPath().bounds(feature(atlas, states));
const [[x0, y0], [x1, y1]] = bounds;
const scale = (WIDTH - PAD * 2) / (x1 - x0);
const height = Math.ceil((y1 - y0) * scale + PAD * 2);
const fit = ([x, y]) => [Math.round(((x - x0) * scale + PAD) * 10) / 10, Math.round(((y - y0) * scale + PAD) * 10) / 10];

/** A path string at one decimal, dropping points that round onto the one before. Rings close. */
function pathOf(geometry) {
  const closed = geometry.type === 'MultiPolygon' || geometry.type === 'Polygon';
  const lines = geometry.type === 'MultiPolygon' ? geometry.coordinates.flat()
    : geometry.type === 'Polygon' || geometry.type === 'MultiLineString' ? geometry.coordinates
      : [geometry.coordinates];
  return lines.map((line) => {
    const points = [];
    for (const point of line.map(fit)) {
      const last = points[points.length - 1];
      if (!last || Math.abs(last[0] - point[0]) >= 0.4 || Math.abs(last[1] - point[1]) >= 0.4) points.push(point);
    }
    if (points.length < 2 || (closed && points.length < 3)) return '';
    return `M${points.map(([x, y]) => `${x} ${y}`).join('L')}${closed ? 'Z' : ''}`;
  }).join('');
}

const cities = Object.fromEntries(Object.entries(CITIES).map(([slug, lonLat]) => {
  const [x, y] = fit(projection(lonLat));
  const [dx, dy] = NUDGE[slug] ?? [0, 0];
  return [slug, { x: Math.round((x + dx) * 10) / 10, y: Math.round((y + dy) * 10) / 10 }];
}));

const source = `// Generated by scripts/art/build-usa-map.mjs from us-atlas (ISC, Mike Bostock), drawn from US Census Bureau boundaries (public domain).
// Do not edit by hand; rerun the script.

export const USA_MAP = {
  width: ${WIDTH},
  height: ${height},
  /** The lower 48's coastline and land borders. */
  outline: '${pathOf(land)}',
  /** Lines between states. */
  states: '${pathOf(borders)}',
  /** Where each game city sits on it. */
  cities: ${JSON.stringify(cities, null, 2).replace(/\n/g, '\n  ')} as Record<string, { x: number; y: number }>,
} as const;
`;
await writeFile(OUT, source, 'utf8');
console.log(`Wrote ${OUT.pathname} (${Math.round(source.length / 1024)} KB, ${WIDTH}x${height}).`);
console.log(cities);
