import type { QuestDefinitionCatalog } from '../types.js';

/**
 * Quest roadmap Phase P: larger rotating goals that sit above the daily board.
 *
 * Weekly contracts deliberately reuse authoritative game activity/history.
 * They grant meaningful but bounded rewards and never permanent progression.
 */
export const weeklyContracts = {
  WEEKLY_STREET_BOSS: {
    key: 'WEEKLY_STREET_BOSS',
    title: 'Street Boss',
    description: 'Mama wants a week that looks like a real operation. Keep the street earning until the take speaks for itself.',
    contactKey: 'MAMA_KING',
    type: 'WEEKLY',
    category: 'STREET',
    difficulty: 'SERIOUS_BUSINESS',
    prerequisites: [],
    objectives: [{
      id: 'street_cash',
      kind: 'EARN_CASH',
      description: 'Earn $500,000 from Scout or street-work shifts.',
      target: 50_000_000,
      params: { eventTypes: ['SCOUT', 'WORK_STREETS'] },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 5_000_000 },
      { kind: 'FAVOR_ITEM', key: 'MAMA_ADVICE', amount: 2 },
      { kind: 'CONTACT_REP', key: 'MAMA_KING', amount: 10 },
    ],
    followUpKeys: [],
    repeatability: 'WEEKLY',
    expiresAfterMinutes: null,
    availability: { rotationPool: 'WEEKLY_CONTRACTS' },
  },

  WEEKLY_ROAD_WARRIOR: {
    key: 'WEEKLY_ROAD_WARRIOR',
    title: 'Road Warrior',
    description: 'Wheels wants proof the highway is part of your business, not a once-in-a-while gamble.',
    contactKey: 'WHEELS',
    type: 'WEEKLY',
    category: 'TRAVEL',
    difficulty: 'SERIOUS_BUSINESS',
    prerequisites: [],
    objectives: [{
      id: 'completed_runs',
      kind: 'EVENT_COUNT',
      description: 'Bring 5 intercity runs home.',
      target: 5,
      params: { eventTypes: ['RUN_RETURNED'] },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 4_000_000 },
      { kind: 'ITEM', key: 'lowRiders', amount: 1 },
      { kind: 'CONTACT_REP', key: 'WHEELS', amount: 10 },
    ],
    followUpKeys: [],
    repeatability: 'WEEKLY',
    expiresAfterMinutes: null,
    availability: { rotationPool: 'WEEKLY_CONTRACTS' },
  },

  WEEKLY_WARLORD: {
    key: 'WEEKLY_WARLORD',
    title: 'Warlord',
    description: 'Tommy says a reputation for muscle only matters if you keep winning when somebody pushes back.',
    contactKey: 'TOMMY',
    type: 'WEEKLY',
    category: 'COMBAT',
    difficulty: 'HIGH_RISK',
    prerequisites: [],
    objectives: [{
      id: 'combat_wins',
      kind: 'WIN_EVENTS',
      description: 'Win 5 offensive fights.',
      target: 5,
      params: { eventTypes: ['RAID_ATTACK', 'DRIVE_BY_ATTACK', 'TURF_PUSH_ATTACK'] },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 6_000_000 },
      { kind: 'FAVOR_ITEM', key: 'TOMMY_VOUCHER', amount: 2 },
      { kind: 'CONTACT_REP', key: 'TOMMY', amount: 10 },
    ],
    followUpKeys: [],
    repeatability: 'WEEKLY',
    expiresAfterMinutes: null,
    availability: { rotationPool: 'WEEKLY_CONTRACTS' },
  },

  WEEKLY_LANDLORD: {
    key: 'WEEKLY_LANDLORD',
    title: 'Landlord',
    description: 'Blocks does not care who takes a corner for ten minutes. Hold real ground long enough that the neighborhood starts treating it as yours.',
    contactKey: 'BLOCKS',
    type: 'WEEKLY',
    category: 'TURF',
    difficulty: 'HIGH_RISK',
    prerequisites: [],
    objectives: [{
      id: 'turf_hours',
      kind: 'TURF_HOLD_HOURS',
      description: 'Accumulate 48 combined hours holding turf.',
      target: 48,
      params: {},
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 5_000_000 },
      { kind: 'FAVOR_ITEM', key: 'DOCTOR_FAVOR', amount: 1 },
      { kind: 'CONTACT_REP', key: 'BLOCKS', amount: 10 },
    ],
    followUpKeys: [],
    repeatability: 'WEEKLY',
    expiresAfterMinutes: null,
    availability: { rotationPool: 'WEEKLY_CONTRACTS' },
  },

  WEEKLY_ENTREPRENEUR: {
    key: 'WEEKLY_ENTREPRENEUR',
    title: 'Entrepreneur',
    description: 'Pip wants turnover. Move enough product through his counter that nobody can call your operation small.',
    contactKey: 'PIP',
    type: 'WEEKLY',
    category: 'PRODUCT',
    difficulty: 'SERIOUS_BUSINESS',
    prerequisites: [],
    objectives: [{
      id: 'product_sales',
      kind: 'EVENT_SUM',
      description: 'Sell $250,000 of product to Pip.',
      target: 25_000_000,
      params: { eventTypes: ['STORE_SELL'], field: 'totalCents', where: { storeKey: 'PIP' } },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 5_000_000 },
      { kind: 'FAVOR_ITEM', key: 'PIP_CONNECTION', amount: 2 },
      { kind: 'CONTACT_REP', key: 'PIP', amount: 10 },
    ],
    followUpKeys: [],
    repeatability: 'WEEKLY',
    expiresAfterMinutes: null,
    availability: { rotationPool: 'WEEKLY_CONTRACTS' },
  },

  WEEKLY_TRAVELER: {
    key: 'WEEKLY_TRAVELER',
    title: 'Traveler',
    description: 'Wheels wants the map opened up. A loop through the same town does not count — put five different city names in the book.',
    contactKey: 'WHEELS',
    type: 'WEEKLY',
    category: 'TRAVEL',
    difficulty: 'SERIOUS_BUSINESS',
    prerequisites: [],
    objectives: [{
      id: 'unique_cities',
      kind: 'UNIQUE_VALUES',
      description: 'Visit 5 different cities on returned runs.',
      target: 5,
      params: { eventTypes: ['RUN_RETURNED'], field: 'cities' },
    }],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 4_000_000 },
      { kind: 'ITEM', key: 'lowRiders', amount: 1 },
      { kind: 'CONTACT_REP', key: 'WHEELS', amount: 10 },
    ],
    followUpKeys: [],
    repeatability: 'WEEKLY',
    expiresAfterMinutes: null,
    availability: { rotationPool: 'WEEKLY_CONTRACTS' },
  },
} as const satisfies QuestDefinitionCatalog;
