import { defineQuestCatalog } from '../quest-definitions.js';

export const storyQuests = defineQuestCatalog({
  FIRST_NIGHT_OUT: {
    key: 'FIRST_NIGHT_OUT',
    title: 'First Night Out',
    description: 'Mama wants to see whether you can make a night on the street pay. Scout any district and learn the basic loop.',
    contactKey: 'MAMA_KING',
    type: 'STORY',
    category: 'STREET',
    difficulty: 'STREET_JOB',
    prerequisites: [],
    objectives: [
      { id: 'scout_turns', kind: 'SPEND_TURNS', description: 'Scout for 12 turns.', target: 12, params: { eventTypes: ['SCOUT'] } },
    ],
    bonusObjectives: [
      { id: 'find_someone', kind: 'RECRUIT_CREW', description: 'Recruit at least one new hoe or thug.', target: 1, params: { eventTypes: ['SCOUT'], crew: 'ANY' } },
    ],
    rewards: [
      { kind: 'CASH', amount: 250000 },
      { kind: 'ITEM', key: 'condoms', amount: 25 },
      { kind: 'ITEM', key: 'beer', amount: 10 },
      { kind: 'CONTACT_REP', key: 'MAMA_KING', amount: 5 },
    ],
    followUpKeys: ['FRESH_FACES'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  FRESH_FACES: {
    key: 'FRESH_FACES',
    title: 'Fresh Faces',
    description: 'A crew needs both workers and muscle. Build enough of each that Mama can start treating you like an operation.',
    contactKey: 'MAMA_KING',
    type: 'STORY',
    category: 'STREET',
    difficulty: 'STREET_JOB',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'FIRST_NIGHT_OUT' } }],
    objectives: [
      { id: 'hoes', kind: 'STATE_AT_LEAST', description: 'Own at least 5 hoes.', target: 5, params: { field: 'whores' } },
      { id: 'thugs', kind: 'STATE_AT_LEAST', description: 'Own at least 5 thugs.', target: 5, params: { field: 'thugs' } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 400000 },
      { kind: 'CONTACT_REP', key: 'MAMA_KING', amount: 10 },
    ],
    followUpKeys: ['KEEPING_THEM_HAPPY'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  KEEPING_THEM_HAPPY: {
    key: 'KEEPING_THEM_HAPPY',
    title: 'Keeping Them Happy',
    description: 'Mama does not care how big the crew looks if everybody walks the first bad night. Put basic supplies on the shelf.',
    contactKey: 'MAMA_KING',
    type: 'STORY',
    category: 'STREET',
    difficulty: 'STREET_JOB',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'FRESH_FACES' } }],
    objectives: [
      { id: 'condoms', kind: 'STATE_AT_LEAST', description: 'Have at least 50 condoms.', target: 50, params: { field: 'condoms' } },
      { id: 'beer', kind: 'STATE_AT_LEAST', description: 'Have at least 25 beer.', target: 25, params: { field: 'beer' } },
      { id: 'crack', kind: 'STATE_AT_LEAST', description: 'Have at least 25 crack.', target: 25, params: { field: 'crack' } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 500000 },
      { kind: 'ITEM', key: 'medicine', amount: 10 },
      { kind: 'CONTACT_REP', key: 'MAMA_KING', amount: 10 },
    ],
    followUpKeys: ['COOKHOUSE'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  COOKHOUSE: {
    key: 'COOKHOUSE',
    title: 'Cookhouse',
    description: 'Pip has customers. Prove you can make product instead of living off whatever the street happens to hand you.',
    contactKey: 'PIP',
    type: 'STORY',
    category: 'PRODUCT',
    difficulty: 'STREET_JOB',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'KEEPING_THEM_HAPPY' } }],
    objectives: [
      { id: 'cook_crack', kind: 'EVENT_SUM', description: 'Produce 100 crack after accepting the job.', target: 100, params: { eventTypes: ['PRODUCE_CRACK'], field: 'product', where: { productType: 'CRACK' } } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 750000 },
      { kind: 'CONTACT_REP', key: 'PIP', amount: 10 },
    ],
    followUpKeys: ['PAYDAY'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  PAYDAY: {
    key: 'PAYDAY',
    title: 'Payday',
    description: 'Mama wants to see that the street can pay the bills. Earn real cash from working the streets after taking the job.',
    contactKey: 'MAMA_KING',
    type: 'STORY',
    category: 'ECONOMY',
    difficulty: 'STREET_JOB',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'COOKHOUSE' } }],
    objectives: [
      { id: 'street_cash', kind: 'EARN_CASH', description: 'Earn $25,000 from Scout trips.', target: 2500000, params: { eventTypes: ['SCOUT'] } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 1000000 },
      { kind: 'CONTACT_REP', key: 'MAMA_KING', amount: 15 },
    ],
    followUpKeys: ['HEAVY_HANDS'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  HEAVY_HANDS: {
    key: 'HEAVY_HANDS',
    title: 'Heavy Hands',
    description: 'Tommy will not open the better rack for somebody who cannot protect a basic crew. Put ten armed thugs on your books.',
    contactKey: 'TOMMY',
    type: 'STORY',
    category: 'COMBAT',
    difficulty: 'CONTRACT',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'PAYDAY' } }],
    objectives: [
      { id: 'armed_thugs', kind: 'STATE_AT_LEAST', description: 'Have at least 10 armed, fit thugs.', target: 10, params: { field: 'armedThugs' } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CONTACT_REP', key: 'TOMMY', amount: 15 },
      { kind: 'WEAPON_ACCESS', key: 'SHOTGUN' },
    ],
    followUpKeys: ['EYES_OPEN'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  EYES_OPEN: {
    key: 'EYES_OPEN',
    title: 'Eyes Open',
    description: 'Tommy does not send people into a house blind. Get a real recon report on another player.',
    contactKey: 'TOMMY',
    type: 'STORY',
    category: 'COMBAT',
    difficulty: 'CONTRACT',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'HEAVY_HANDS' } }],
    objectives: [
      { id: 'recon', kind: 'EVENT_COUNT', description: 'Recon another player.', target: 1, params: { eventTypes: ['COMBAT_RECON'] } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 750000 },
      { kind: 'CONTACT_REP', key: 'TOMMY', amount: 10 },
    ],
    followUpKeys: ['COLLECTION_DAY'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  COLLECTION_DAY: {
    key: 'COLLECTION_DAY',
    title: 'Collection Day',
    description: 'You looked. Now act on the information. Win a raid and come back with proof you can collect.',
    contactKey: 'TOMMY',
    type: 'STORY',
    category: 'COMBAT',
    difficulty: 'SERIOUS_BUSINESS',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'EYES_OPEN' } }],
    objectives: [
      { id: 'raid_win', kind: 'WIN_EVENTS', description: 'Win one raid.', target: 1, params: { eventTypes: ['RAID_ATTACK'] } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 1250000 },
      { kind: 'CONTACT_REP', key: 'TOMMY', amount: 20 },
      { kind: 'WEAPON_ACCESS', key: 'TEK9' },
    ],
    followUpKeys: ['PACK_YOUR_BAGS'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  PACK_YOUR_BAGS: {
    key: 'PACK_YOUR_BAGS',
    title: 'Pack Your Bags',
    description: 'Wheels wants to know whether your operation can leave home without falling apart. Put a real run on the road.',
    contactKey: 'WHEELS',
    type: 'STORY',
    category: 'TRAVEL',
    difficulty: 'CONTRACT',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'COLLECTION_DAY' } }],
    objectives: [
      { id: 'run', kind: 'EVENT_COUNT', description: 'Launch one intercity run.', target: 1, params: { eventTypes: ['RUN_LAUNCHED'] } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 1500000 },
      { kind: 'CONTACT_REP', key: 'WHEELS', amount: 15 },
    ],
    followUpKeys: ['PLANT_THE_FLAG'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  PLANT_THE_FLAG: {
    key: 'PLANT_THE_FLAG',
    title: 'Plant the Flag',
    description: 'Blocks has watched you make money, fight and move product. Now take a corner and prove you can hold something that matters.',
    contactKey: 'BLOCKS',
    type: 'STORY',
    category: 'TURF',
    difficulty: 'SERIOUS_BUSINESS',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'PACK_YOUR_BAGS' } }],
    objectives: [
      { id: 'claim', kind: 'WIN_EVENTS', description: 'Successfully claim one city block.', target: 1, params: { eventTypes: ['TURF_CLAIM'] } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 2000000 },
      { kind: 'CONTACT_REP', key: 'BLOCKS', amount: 20 },
      { kind: 'WEAPON_ACCESS', key: 'AK47' },
    ],
    followUpKeys: [],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },
});
