import { defineQuestCatalog } from '../quest-definitions.js';

export const storyQuests = defineQuestCatalog({
  FIRST_NIGHT_OUT: {
    key: 'FIRST_NIGHT_OUT',
    title: 'First Night Out',
    description: 'Mama wants to see whether you can make a night on the street pay. Scout any district and learn the basic loop.',
    story: {
      chapter: 'Lesson 1: Work the block',
      intro: 'Mama King folds a street map until only five corners show. "Do not chase legend tonight. Pick a block, spend real turns, and come back with money you can count."',
      inProgress: 'Mama keeps it simple: the street teaches faster than any lecture. Scout a district, watch the take, and notice who joins when you put time in.',
      ready: '"Good," Mama says. "Now you know what a turn is worth when you spend it with both eyes open."',
      completed: 'Mama sends you back out with basic shelf stock and a warning: one clean night is a start, not a business.',
      lesson: 'Scouting spends turns to earn cash and recruit crew. Bigger scouting trips make the core loop easier to read.',
      actionHint: 'Open Scout, choose any district, and spend 12 turns.',
    },
    contactKey: 'MAMA_KING',
    type: 'STORY',
    category: 'STREET',
    difficulty: 'STREET_JOB',
    prerequisites: [],
    objectives: [
      { id: 'scout_turns', kind: 'SPEND_TURNS', description: 'Scout for 12 turns.', target: 12, params: { eventTypes: ['SCOUT'] } },
    ],
    bonusObjectives: [
      { id: 'find_someone', kind: 'RECRUIT_CREW', description: 'Recruit at least one new hoe or thug.', target: 1, params: { eventTypes: ['SCOUT'], crew: 'ANY' } },
    ],
    rewards: [
      { kind: 'CASH', amount: 250000 },
      { kind: 'ITEM', key: 'condoms', amount: 25 },
      { kind: 'ITEM', key: 'beer', amount: 10 },
      { kind: 'CONTACT_REP', key: 'MAMA_KING', amount: 5 },
    ],
    followUpKeys: ['FRESH_FACES'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  FRESH_FACES: {
    key: 'FRESH_FACES',
    title: 'Fresh Faces',
    description: 'A crew needs both workers and muscle. Build enough of each that Mama can start treating you like an operation.',
    story: {
      chapter: 'Lesson 2: Balance the crew',
      intro: '"Money walks in on two feet," Mama says, tapping one finger for workers and one for muscle. "Lean too hard either way and the block smells weakness."',
      inProgress: 'Mama is watching the shape of the crew, not just the size. Bring in enough workers to earn and enough thugs to keep order.',
      ready: '"Now it looks like a crew," Mama says. "Still small. Small can move quick."',
      completed: 'Mama starts using the word operation, but only after making sure you heard the responsibility hiding inside it.',
      lesson: 'Workers drive income, while thugs protect the street and later carry combat plans. Early growth needs both.',
      actionHint: 'Scout districts until you own at least 5 hoes and 5 thugs.',
    },
    contactKey: 'MAMA_KING',
    type: 'STORY',
    category: 'STREET',
    difficulty: 'STREET_JOB',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'FIRST_NIGHT_OUT' } }],
    objectives: [
      { id: 'hoes', kind: 'STATE_AT_LEAST', description: 'Own at least 5 hoes.', target: 5, params: { field: 'whores' } },
      { id: 'thugs', kind: 'STATE_AT_LEAST', description: 'Own at least 5 thugs.', target: 5, params: { field: 'thugs' } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 400000 },
      { kind: 'CONTACT_REP', key: 'MAMA_KING', amount: 10 },
    ],
    followUpKeys: ['KEEPING_THEM_HAPPY'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  KEEPING_THEM_HAPPY: {
    key: 'KEEPING_THEM_HAPPY',
    title: 'Keeping Them Happy',
    description: 'Mama does not care how big the crew looks if everybody walks the first bad night. Put basic supplies on the shelf.',
    story: {
      chapter: 'Lesson 3: Stock the shelves',
      intro: 'Mama points at the stash room before she looks at the crew. "Hungry people leave. Sick people cost you. Empty shelves turn a good night mean."',
      inProgress: 'Mama wants proof you can keep supplies ahead of demand. Condoms, beer, and crack keep different parts of the street from turning on you.',
      ready: '"That shelf buys you patience," Mama says. "Patience buys you choices."',
      completed: 'Mama leaves medicine on the counter and tells you the city is kinder to crews that prepare before trouble arrives.',
      lesson: 'Crew happiness and health depend on supplies. Buying ahead helps prevent departures and bad action results.',
      actionHint: 'Visit the stores and build stockpiles of condoms, beer, and crack.',
    },
    contactKey: 'MAMA_KING',
    type: 'STORY',
    category: 'STREET',
    difficulty: 'STREET_JOB',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'FRESH_FACES' } }],
    objectives: [
      { id: 'condoms', kind: 'STATE_AT_LEAST', description: 'Have at least 50 condoms.', target: 50, params: { field: 'condoms' } },
      { id: 'beer', kind: 'STATE_AT_LEAST', description: 'Have at least 25 beer.', target: 25, params: { field: 'beer' } },
      { id: 'crack', kind: 'STATE_AT_LEAST', description: 'Have at least 25 crack.', target: 25, params: { field: 'crack' } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 500000 },
      { kind: 'ITEM', key: 'medicine', amount: 10 },
      { kind: 'CONTACT_REP', key: 'MAMA_KING', amount: 10 },
    ],
    followUpKeys: ['COOKHOUSE'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  COOKHOUSE: {
    key: 'COOKHOUSE',
    title: 'Cookhouse',
    description: 'Pip has customers. Prove you can make product instead of living off whatever the street happens to hand you.',
    story: {
      chapter: 'Lesson 4: Make your own supply',
      intro: 'Pip smiles like every shortage is personally offended by him. "Buying is fine. Cooking is control. Show me you can feed your own counter."',
      inProgress: 'Pip wants product made after you take the job, not old rocks from the back shelf. Put thugs to work and watch the output.',
      ready: '"There it is," Pip says. "Not enough to brag. Enough to stop begging the market every time it sneezes."',
      completed: 'Pip pays quickly, already talking about customers you have not met yet and prices you have not learned to fear.',
      lesson: 'Production turns thugs and turns into product. It gives you inventory even when store supply or market prices are rough.',
      actionHint: 'Open Produce and cook at least 100 crack after accepting this job.',
    },
    contactKey: 'PIP',
    type: 'STORY',
    category: 'PRODUCT',
    difficulty: 'STREET_JOB',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'KEEPING_THEM_HAPPY' } }],
    objectives: [
      { id: 'cook_crack', kind: 'EVENT_SUM', description: 'Produce 100 crack after accepting the job.', target: 100, params: { eventTypes: ['PRODUCE_CRACK'], field: 'product', where: { productType: 'CRACK' } } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 750000 },
      { kind: 'CONTACT_REP', key: 'PIP', amount: 10 },
    ],
    followUpKeys: ['PAYDAY'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  PAYDAY: {
    key: 'PAYDAY',
    title: 'Payday',
    description: 'Mama wants to see that the street can pay the bills. Earn real cash from working the streets after taking the job.',
    story: {
      chapter: 'Lesson 5: Read the take',
      intro: 'Mama lays out bills in flat stacks. "Product matters. Muscle matters. But cash is the truth everybody understands."',
      inProgress: 'Mama is measuring fresh street income. Scout runs after accepting this job count toward proving the operation can fund itself.',
      ready: '"That is a payday," Mama says. "Now learn how fast payday turns into payroll."',
      completed: 'Mama lets the silence sit over the money before she nods toward the bigger tables in the room.',
      lesson: 'Scouting remains a cash engine, and district choice changes how much your crew brings home.',
      actionHint: 'Scout districts until fresh Scout income reaches $25,000.',
    },
    contactKey: 'MAMA_KING',
    type: 'STORY',
    category: 'ECONOMY',
    difficulty: 'STREET_JOB',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'COOKHOUSE' } }],
    objectives: [
      { id: 'street_cash', kind: 'EARN_CASH', description: 'Earn $25,000 from Scout trips.', target: 2500000, params: { eventTypes: ['SCOUT'] } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 1000000 },
      { kind: 'CONTACT_REP', key: 'MAMA_KING', amount: 15 },
    ],
    followUpKeys: ['HEAVY_HANDS'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  HEAVY_HANDS: {
    key: 'HEAVY_HANDS',
    title: 'Heavy Hands',
    description: 'Tommy will not open the better rack for somebody who cannot protect a basic crew. Put ten armed thugs on your books.',
    story: {
      chapter: 'Lesson 6: Arm the muscle',
      intro: 'Tommy checks the room once, then the exits twice. "Unarmed muscle is a rumor. Put steel in enough hands and I will sell you the next shelf."',
      inProgress: 'Tommy is not impressed by headcount alone. Fit thugs need weapons before they count as armed protection.',
      ready: '"Ten that can stand up," Tommy says. "Fine. Shotguns are on the table."',
      completed: 'Tommy unlocks better buying access without ceremony. The lesson is the ceremony.',
      lesson: 'Combat strength depends on fit crew and weapons. Better weapon access starts with proving you can arm basics.',
      actionHint: 'Buy weapons and keep at least 10 fit thugs armed.',
    },
    contactKey: 'TOMMY',
    type: 'STORY',
    category: 'COMBAT',
    difficulty: 'CONTRACT',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'PAYDAY' } }],
    objectives: [
      { id: 'armed_thugs', kind: 'STATE_AT_LEAST', description: 'Have at least 10 armed, fit thugs.', target: 10, params: { field: 'armedThugs' } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CONTACT_REP', key: 'TOMMY', amount: 15 },
      { kind: 'WEAPON_ACCESS', key: 'SHOTGUN' },
    ],
    followUpKeys: ['EYES_OPEN'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  EYES_OPEN: {
    key: 'EYES_OPEN',
    title: 'Eyes Open',
    description: 'Tommy does not send people into a house blind. Get a real recon report on another player.',
    story: {
      chapter: 'Lesson 7: Look before trouble',
      intro: 'Tommy slides a recon note across the table without letting go. "Want to hit somebody? First learn what hitting blind costs."',
      inProgress: 'Tommy wants a report, not a guess. Recon another player so targets become decisions instead of coin flips.',
      ready: '"Now you have facts," Tommy says. "Facts do not make you brave. They make you less stupid."',
      completed: 'Tommy files the report away and starts talking about collections like the outcome is already half decided.',
      lesson: 'Recon gives combat intelligence before a raid. Information helps you choose targets and avoid bad fights.',
      actionHint: 'Open Combat and recon another player.',
    },
    contactKey: 'TOMMY',
    type: 'STORY',
    category: 'COMBAT',
    difficulty: 'CONTRACT',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'HEAVY_HANDS' } }],
    objectives: [
      { id: 'recon', kind: 'EVENT_COUNT', description: 'Recon another player.', target: 1, params: { eventTypes: ['COMBAT_RECON'] } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 750000 },
      { kind: 'CONTACT_REP', key: 'TOMMY', amount: 10 },
    ],
    followUpKeys: ['COLLECTION_DAY'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  COLLECTION_DAY: {
    key: 'COLLECTION_DAY',
    title: 'Collection Day',
    description: 'You looked. Now act on the information. Win a raid and come back with proof you can collect.',
    story: {
      chapter: 'Lesson 8: Commit to a fight',
      intro: 'Tommy does not raise his voice. He does not need to. "You saw the house. Now decide if you are built to knock."',
      inProgress: 'Tommy is looking for one clean win. Pick a target you understand, send a crew that can survive, and bring back proof.',
      ready: '"That is a collection," Tommy says. "Not a war. Not yet."',
      completed: 'Tommy opens another rack and lets the heavier metal explain what comes next.',
      lesson: 'Raids resolve risk for loot and pressure. Winning depends on target choice, crew condition, and weapon strength.',
      actionHint: 'Use Combat to win one raid against another player.',
    },
    contactKey: 'TOMMY',
    type: 'STORY',
    category: 'COMBAT',
    difficulty: 'SERIOUS_BUSINESS',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'EYES_OPEN' } }],
    objectives: [
      { id: 'raid_win', kind: 'WIN_EVENTS', description: 'Win one raid.', target: 1, params: { eventTypes: ['RAID_ATTACK'] } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 1250000 },
      { kind: 'CONTACT_REP', key: 'TOMMY', amount: 20 },
      { kind: 'WEAPON_ACCESS', key: 'TEK9' },
    ],
    followUpKeys: ['PACK_YOUR_BAGS'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  PACK_YOUR_BAGS: {
    key: 'PACK_YOUR_BAGS',
    title: 'Pack Your Bags',
    description: 'Wheels wants to know whether your operation can leave home without falling apart. Put a real run on the road.',
    story: {
      chapter: 'Lesson 9: Leave home loaded',
      intro: 'Wheels jingles keys like punctuation. "A corner is one thing. A route is a promise that your people can move without spilling the whole bag."',
      inProgress: 'Wheels wants a run launched, not a speech. Put cars, crew, cash, or product on the road and learn how distance changes risk.',
      ready: '"Now you are on the map," Wheels says. "Roads pay different because roads bite different."',
      completed: 'Wheels marks the route in pencil. Nothing about the roads stays still long enough for ink.',
      lesson: 'Travel opens intercity opportunity and road risk. Runs can move money and product beyond your home city.',
      actionHint: 'Open Travel and launch one intercity run.',
    },
    contactKey: 'WHEELS',
    type: 'STORY',
    category: 'TRAVEL',
    difficulty: 'CONTRACT',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'COLLECTION_DAY' } }],
    objectives: [
      { id: 'run', kind: 'EVENT_COUNT', description: 'Launch one intercity run.', target: 1, params: { eventTypes: ['RUN_LAUNCHED'] } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 1500000 },
      { kind: 'CONTACT_REP', key: 'WHEELS', amount: 15 },
    ],
    followUpKeys: ['PLANT_THE_FLAG'],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },

  PLANT_THE_FLAG: {
    key: 'PLANT_THE_FLAG',
    title: 'Plant the Flag',
    description: 'Blocks has watched you make money, fight and move product. Now take a corner and prove you can hold something that matters.',
    story: {
      chapter: 'Lesson 10: Take ground',
      intro: 'Blocks studies ownership lines like weather. "Cash gets spent. Product gets sold. Turf stays loud after you leave."',
      inProgress: 'Blocks wants a claimed block. Choose ground you can contest, push in, and make the map remember your name.',
      ready: '"There," Blocks says. "A corner with your weight on it. Now everybody nearby has an opinion."',
      completed: 'Blocks records the claim and stops calling you new. That may be praise. It may be a warning.',
      lesson: 'Turf turns local strength into territory. Claimed blocks can anchor city control and later systems.',
      actionHint: 'Open Turf and successfully claim one city block.',
    },
    contactKey: 'BLOCKS',
    type: 'STORY',
    category: 'TURF',
    difficulty: 'SERIOUS_BUSINESS',
    prerequisites: [{ kind: 'QUEST_COMPLETED', params: { questKey: 'PACK_YOUR_BAGS' } }],
    objectives: [
      { id: 'claim', kind: 'WIN_EVENTS', description: 'Successfully claim one city block.', target: 1, params: { eventTypes: ['TURF_CLAIM'] } },
    ],
    bonusObjectives: [],
    rewards: [
      { kind: 'CASH', amount: 2000000 },
      { kind: 'CONTACT_REP', key: 'BLOCKS', amount: 20 },
      { kind: 'WEAPON_ACCESS', key: 'AK47' },
    ],
    followUpKeys: [],
    repeatability: 'ONCE',
    expiresAfterMinutes: null,
    availability: {},
  },
});
